# Embeddings

In [ ]:
import torch
import torch.nn as nn

In [ ]:
embeds=nn.Embedding(2,10) # 2 words in vocab, 10 dimensional embeddings

print(embeds.weight)
print(embeds.weight.shape)

Parameter containing:
tensor([[ 1.5263, -0.2119,  0.1418,  0.4774, -0.6002,  2.3424, -1.0802,  0.0156,
          2.1953, -1.2679],
        [ 0.1563, -0.3765, -0.5474,  0.5681, -0.7988, -2.4929,  0.9906, -0.6768,
         -0.6133,  2.1027]], requires_grad=True)
torch.Size([2, 10])


In [ ]:
word_to_idx={"hello":0,"world":1}
sentence="hello hello world"
words=sentence.split()
print(words)

['hello', 'hello', 'world']


In [ ]:
indices=[word_to_idx[w] for w in words]
print(indices)

[0, 0, 1]


In [ ]:
indices_tensor=torch.tensor(indices,dtype=torch.long)
indices_tensor

tensor([0, 0, 1])

In [ ]:
emb=embeds(indices_tensor)
print(emb.shape)
print(emb)

torch.Size([3, 10])
tensor([[ 1.5263, -0.2119,  0.1418,  0.4774, -0.6002,  2.3424, -1.0802,  0.0156,
          2.1953, -1.2679],
        [ 1.5263, -0.2119,  0.1418,  0.4774, -0.6002,  2.3424, -1.0802,  0.0156,
          2.1953, -1.2679],
        [ 0.1563, -0.3765, -0.5474,  0.5681, -0.7988, -2.4929,  0.9906, -0.6768,
         -0.6133,  2.1027]], grad_fn=<EmbeddingBackward0>)
